// Copyright 2025 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

/*******************************************************************************
  88888888888 888      d8b                .d888 d8b 888               d8b
      888     888      Y8P               d88P"  Y8P 888               Y8P
      888     888                        888        888
      888     88888b.  888 .d8888b       888888 888 888  .d88b.       888 .d8888b
      888     888 "88b 888 88K           888    888 888 d8P  Y8b      888 88K
      888     888  888 888 "Y8888b.      888    888 888 88888888      888 "Y8888b.
      888     888  888 888      X88      888    888 888 Y8b.          888      X88
      888     888  888 888  88888P'      888    888 888  "Y8888       888  88888P'
                                                        888                 888
                                                        888                 888
                                                        888                 888
     .d88b.   .d88b.  88888b.   .d88b.  888d888 8888b.  888888 .d88b.   .d88888
    d88P"88b d8P  Y8b 888 "88b d8P  Y8b 888P"      "88b 888   d8P  Y8b d88" 888
    888  888 88888888 888  888 88888888 888    .d888888 888   88888888 888  888
    Y88b 888 Y8b.     888  888 Y8b.     888    888  888 Y88b. Y8b.     Y88b 888
     "Y88888  "Y8888  888  888  "Y8888  888    "Y888888  "Y888 "Y8888   "Y88888
         888
    Y8b d88P
     "Y88P"
*******************************************************************************/

#pragma once

#ifndef DIODE_DIRECTION
#    define DIODE_DIRECTION COL2ROW
#endif // DIODE_DIRECTION

#ifndef RGB_MATRIX_MAXIMUM_BRIGHTNESS
#    define RGB_MATRIX_MAXIMUM_BRIGHTNESS 150
#endif // RGB_MATRIX_MAXIMUM_BRIGHTNESS

#ifndef RGB_MATRIX_SAT_STEP
#    define RGB_MATRIX_SAT_STEP 8
#endif // RGB_MATRIX_SAT_STEP

#ifndef RGB_MATRIX_SLEEP
#    define RGB_MATRIX_SLEEP
#endif // RGB_MATRIX_SLEEP

#ifndef RGB_MATRIX_SPD_STEP
#    define RGB_MATRIX_SPD_STEP 10
#endif // RGB_MATRIX_SPD_STEP

#ifndef RGB_MATRIX_VAL_STEP
#    define RGB_MATRIX_VAL_STEP 8
#endif // RGB_MATRIX_VAL_STEP

#ifndef RGB_MATRIX_LED_COUNT
#    define RGB_MATRIX_LED_COUNT 66
#endif // RGB_MATRIX_LED_COUNT

#ifndef RGBLIGHT_LED_COUNT
#    define RGBLIGHT_LED_COUNT 66
#endif // RGBLIGHT_LED_COUNT

#ifndef USB_SUSPEND_WAKEUP_DELAY
#    define USB_SUSPEND_WAKEUP_DELAY 5000
#endif // USB_SUSPEND_WAKEUP_DELAY

#ifndef WS2812_DI_PIN
#    define WS2812_DI_PIN E6
#endif // WS2812_DI_PIN

#ifndef LAYOUT_all
#    define LAYOUT_all LAYOUT
#endif // LAYOUT_all

#ifndef DEVICE_VER
#    define DEVICE_VER 0x0001
#endif // DEVICE_VER

#ifndef MANUFACTURER
#    define MANUFACTURER "KBDfans"
#endif // MANUFACTURER

#ifndef PRODUCT
#    define PRODUCT "Baguette66 RGB"
#endif // PRODUCT

#ifndef PRODUCT_ID
#    define PRODUCT_ID 0x0106
#endif // PRODUCT_ID

#ifndef VENDOR_ID
#    define VENDOR_ID 0x4B42
#endif // VENDOR_ID

#ifndef MATRIX_COLS
#    define MATRIX_COLS 15
#endif // MATRIX_COLS

#ifndef MATRIX_ROWS
#    define MATRIX_ROWS 5
#endif // MATRIX_ROWS

#ifndef MATRIX_COL_PINS
#    define MATRIX_COL_PINS { C6, C7, F7, F6, B0, B1, B2, B3, D0, D1, D2, D3, D5, D4, D6 }
#endif // MATRIX_COL_PINS

#ifndef MATRIX_ROW_PINS
#    define MATRIX_ROW_PINS { F0, F1, F4, F5, B6 }
#endif // MATRIX_ROW_PINS

#ifndef RGB_MATRIX_DEFAULT_MODE
#    define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CYCLE_ALL
#endif // RGB_MATRIX_DEFAULT_MODE

#ifndef ENABLE_RGB_MATRIX_ALPHAS_MODS
#    define ENABLE_RGB_MATRIX_ALPHAS_MODS
#endif // ENABLE_RGB_MATRIX_ALPHAS_MODS

#ifndef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#    define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#endif // ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT

#ifndef ENABLE_RGB_MATRIX_BREATHING
#    define ENABLE_RGB_MATRIX_BREATHING
#endif // ENABLE_RGB_MATRIX_BREATHING

#ifndef ENABLE_RGB_MATRIX_BAND_VAL
#    define ENABLE_RGB_MATRIX_BAND_VAL
#endif // ENABLE_RGB_MATRIX_BAND_VAL

#ifndef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#    define ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#endif // ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL

#ifndef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#    define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#endif // ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL

#ifndef ENABLE_RGB_MATRIX_CYCLE_ALL
#    define ENABLE_RGB_MATRIX_CYCLE_ALL
#endif // ENABLE_RGB_MATRIX_CYCLE_ALL

#ifndef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#    define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#endif // ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT

#ifndef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#    define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#endif // ENABLE_RGB_MATRIX_CYCLE_UP_DOWN

#ifndef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#    define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#endif // ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON

#ifndef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#    define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#endif // ENABLE_RGB_MATRIX_CYCLE_OUT_IN

#ifndef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#    define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#endif // ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL

#ifndef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#    define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#endif // ENABLE_RGB_MATRIX_CYCLE_PINWHEEL

#ifndef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#    define ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#endif // ENABLE_RGB_MATRIX_CYCLE_SPIRAL

#ifndef ENABLE_RGB_MATRIX_DUAL_BEACON
#    define ENABLE_RGB_MATRIX_DUAL_BEACON
#endif // ENABLE_RGB_MATRIX_DUAL_BEACON

#ifndef ENABLE_RGB_MATRIX_RAINBOW_BEACON
#    define ENABLE_RGB_MATRIX_RAINBOW_BEACON
#endif // ENABLE_RGB_MATRIX_RAINBOW_BEACON

#ifndef ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#    define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#endif // ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS

#ifndef ENABLE_RGB_MATRIX_RAINDROPS
#    define ENABLE_RGB_MATRIX_RAINDROPS
#endif // ENABLE_RGB_MATRIX_RAINDROPS

#ifndef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#    define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#endif // ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS

#ifndef ENABLE_RGB_MATRIX_HUE_BREATHING
#    define ENABLE_RGB_MATRIX_HUE_BREATHING
#endif // ENABLE_RGB_MATRIX_HUE_BREATHING

#ifndef ENABLE_RGB_MATRIX_HUE_PENDULUM
#    define ENABLE_RGB_MATRIX_HUE_PENDULUM
#endif // ENABLE_RGB_MATRIX_HUE_PENDULUM

#ifndef ENABLE_RGB_MATRIX_HUE_WAVE
#    define ENABLE_RGB_MATRIX_HUE_WAVE
#endif // ENABLE_RGB_MATRIX_HUE_WAVE

#ifndef ENABLE_RGB_MATRIX_PIXEL_RAIN
#    define ENABLE_RGB_MATRIX_PIXEL_RAIN
#endif // ENABLE_RGB_MATRIX_PIXEL_RAIN

#ifndef ENABLE_RGB_MATRIX_PIXEL_FLOW
#    define ENABLE_RGB_MATRIX_PIXEL_FLOW
#endif // ENABLE_RGB_MATRIX_PIXEL_FLOW

#ifndef ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#    define ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#endif // ENABLE_RGB_MATRIX_PIXEL_FRACTAL

#ifndef ENABLE_RGB_MATRIX_TYPING_HEATMAP
#    define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#endif // ENABLE_RGB_MATRIX_TYPING_HEATMAP

#ifndef RGBLIGHT_EFFECT_BREATHING
#    define RGBLIGHT_EFFECT_BREATHING
#endif // RGBLIGHT_EFFECT_BREATHING

#ifndef RGBLIGHT_EFFECT_RAINBOW_MOOD
#    define RGBLIGHT_EFFECT_RAINBOW_MOOD
#endif // RGBLIGHT_EFFECT_RAINBOW_MOOD

#ifndef RGBLIGHT_EFFECT_RAINBOW_SWIRL
#    define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#endif // RGBLIGHT_EFFECT_RAINBOW_SWIRL

#ifndef RGBLIGHT_EFFECT_SNAKE
#    define RGBLIGHT_EFFECT_SNAKE
#endif // RGBLIGHT_EFFECT_SNAKE

#ifndef RGBLIGHT_EFFECT_KNIGHT
#    define RGBLIGHT_EFFECT_KNIGHT
#endif // RGBLIGHT_EFFECT_KNIGHT

#ifndef RGBLIGHT_EFFECT_CHRISTMAS
#    define RGBLIGHT_EFFECT_CHRISTMAS
#endif // RGBLIGHT_EFFECT_CHRISTMAS

#ifndef RGBLIGHT_EFFECT_STATIC_GRADIENT
#    define RGBLIGHT_EFFECT_STATIC_GRADIENT
#endif // RGBLIGHT_EFFECT_STATIC_GRADIENT

#ifndef RGBLIGHT_EFFECT_RGB_TEST
#    define RGBLIGHT_EFFECT_RGB_TEST
#endif // RGBLIGHT_EFFECT_RGB_TEST

#ifndef RGBLIGHT_EFFECT_ALTERNATING
#    define RGBLIGHT_EFFECT_ALTERNATING
#endif // RGBLIGHT_EFFECT_ALTERNATING

#ifndef RGBLIGHT_EFFECT_TWINKLE
#    define RGBLIGHT_EFFECT_TWINKLE
#endif // RGBLIGHT_EFFECT_TWINKLE
